# Generated by Django 2.1.7 on 2019-03-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FTIRSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('wavenumber', models.FloatField()),
                ('absorbance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FTIRSpectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1000)),
                ('preparation', models.CharField(choices=[('H', 'Human'), ('R', 'Robot'), ('C', 'Cell')], max_length=1)),
                ('LIPF6_mass_ratio', models.FloatField(blank=True, null=True)),
                ('EC_mass_ratio', models.FloatField(blank=True, null=True)),
                ('EMC_mass_ratio', models.FloatField(blank=True, null=True)),
                ('DMC_mass_ratio', models.FloatField(blank=True, null=True)),
                ('DEC_mass_ratio', models.FloatField(blank=True, null=True)),
                ('supervised', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='ftirsample',
            name='spectrum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FTIR_to_electrolyte_composition.FTIRSpectrum'),
        ),
    ]
