# Generated by Django 2.1.7 on 2019-04-03 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FTIR_to_electrolyte_composition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='ftirspectrum',
            name='experiment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FTIR_to_electrolyte_composition.Experiment'),
        ),
    ]
